### ISSUE TITLE
Is possible to integrate with buf.build? 

### ISSUE THREAD

**Issue by khafidprayoga** [favadi/protoc-go-inject-tag#59]
I am trying to use this library, to integrate with modern build system called http://buf.build

```yaml
plugins:
  - name: go
    out: pb
    opt: paths=source_relative
  - plugin: buf.build/grpc/go
    out: pb
    opt:
      - paths=source_relative
  - name: go-inject-tag
    out: .
    opt:
      - paths=source_relative
      - input: "*.pb.go"
```

 But it throws an error with exit code 1 
      
       **Failure: could not convert element map[string]interface {} to a string**
